on: [push, pull_request]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://git@codeberg.org/LocalCharts/forest.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
          GIT_SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          GIT_SSH_NO_VERIFY_HOST: "true"
          GIT_USERNAME: git
          GIT_SSH_PUBLIC_KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP63xGtELUDp7ni17dnIX7vgvpiRK2Y1O9oWHJB1E3by o@red-special"
